package com.qf.dao.pojo;
// Generated 2017-7-11 12:41:52 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TTrain generated by hbm2java
 */
public class TTrain implements java.io.Serializable {

	private String id;
	private TStation TStationByEndstation;
	private TStation TStationByStartstation;
	private Date starttime;
	private Date endtime;
	private int mile;
	private int noseatnumber;
	private int bodytype;
	private int type;
	private String con1;
	private String con2;
	private String con3;
	private String con4;
	private String con5;
	private Set TRoutes = new HashSet(0);
	private Set TTickets = new HashSet(0);
	private Set TCarriages = new HashSet(0);

	public TTrain() {
	}

	public TTrain(String id, TStation TStationByEndstation, TStation TStationByStartstation, Date starttime,
			Date endtime, int mile, int noseatnumber, int bodytype, int type) {
		this.id = id;
		this.TStationByEndstation = TStationByEndstation;
		this.TStationByStartstation = TStationByStartstation;
		this.starttime = starttime;
		this.endtime = endtime;
		this.mile = mile;
		this.noseatnumber = noseatnumber;
		this.bodytype = bodytype;
		this.type = type;
	}

	public TTrain(String id, TStation TStationByEndstation, TStation TStationByStartstation, Date starttime,
			Date endtime, int mile, int noseatnumber, int bodytype, int type, String con1,
			String con2, String con3, String con4, String con5, Set TRoutes) {
		this.id = id;
		this.TStationByEndstation = TStationByEndstation;
		this.TStationByStartstation = TStationByStartstation;
		this.starttime = starttime;
		this.endtime = endtime;
		this.mile = mile;
		this.noseatnumber = noseatnumber;
		this.bodytype = bodytype;
		this.type = type;
		this.con1 = con1;
		this.con2 = con2;
		this.con3 = con3;
		this.con4 = con4;
		this.con5 = con5;
		this.TRoutes = TRoutes;
		this.TTickets = TTickets;
		this.TCarriages = TCarriages;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public TStation getTStationByEndstation() {
		return this.TStationByEndstation;
	}

	public void setTStationByEndstation(TStation TStationByEndstation) {
		this.TStationByEndstation = TStationByEndstation;
	}

	public TStation getTStationByStartstation() {
		return this.TStationByStartstation;
	}

	public void setTStationByStartstation(TStation TStationByStartstation) {
		this.TStationByStartstation = TStationByStartstation;
	}

	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	public int getMile() {
		return this.mile;
	}

	public void setMile(int mile) {
		this.mile = mile;
	}

	public int getNoseatnumber() {
		return this.noseatnumber;
	}

	public void setNoseatnumber(int noseatnumber) {
		this.noseatnumber = noseatnumber;
	}

	public int getBodytype() {
		return this.bodytype;
	}

	public void setBodytype(int bodytype) {
		this.bodytype = bodytype;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public String getCon1() {
		return this.con1;
	}

	public void setCon1(String con1) {
		this.con1 = con1;
	}

	public String getCon2() {
		return this.con2;
	}

	public void setCon2(String con2) {
		this.con2 = con2;
	}

	public String getCon3() {
		return this.con3;
	}

	public void setCon3(String con3) {
		this.con3 = con3;
	}

	public String getCon4() {
		return this.con4;
	}

	public void setCon4(String con4) {
		this.con4 = con4;
	}

	public String getCon5() {
		return this.con5;
	}

	public void setCon5(String con5) {
		this.con5 = con5;
	}

	public Set getTRoutes() {
		return this.TRoutes;
	}

	public void setTRoutes(Set TRoutes) {
		this.TRoutes = TRoutes;
	}

	public Set getTTickets() {
		return this.TTickets;
	}

	public void setTTickets(Set TTickets) {
		this.TTickets = TTickets;
	}

	public Set getTCarriages() {
		return this.TCarriages;
	}

	public void setTCarriages(Set TCarriages) {
		this.TCarriages = TCarriages;
	}

}
