package com.qf.dao.pojo;
// Generated 2017-7-11 12:41:52 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TOrders generated by hbm2java
 */
public class TOrders implements java.io.Serializable {

	private int id;
	private TTicket TTicket;
	private TUser TUser;
	private int status;
	private Date maketime;
	private String con1;
	private String con2;
	private String con3;
	private String con4;
	private String con5;

	public TOrders() {
	}

	public TOrders(int id, TTicket TTicket, TUser TUser, int status, Date maketime) {
		this.id = id;
		this.TTicket = TTicket;
		this.TUser = TUser;
		this.status = status;
		this.maketime = maketime;
	}

	public TOrders(int id, TTicket TTicket, TUser TUser, int status, Date maketime, String con1,
			String con2, String con3, String con4, String con5) {
		this.id = id;
		this.TTicket = TTicket;
		this.TUser = TUser;
		this.status = status;
		this.maketime = maketime;
		this.con1 = con1;
		this.con2 = con2;
		this.con3 = con3;
		this.con4 = con4;
		this.con5 = con5;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public TTicket getTTicket() {
		return this.TTicket;
	}

	public void setTTicket(TTicket TTicket) {
		this.TTicket = TTicket;
	}

	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Date getMaketime() {
		return this.maketime;
	}

	public void setMaketime(Date maketime) {
		this.maketime = maketime;
	}

	public String getCon1() {
		return this.con1;
	}

	public void setCon1(String con1) {
		this.con1 = con1;
	}

	public String getCon2() {
		return this.con2;
	}

	public void setCon2(String con2) {
		this.con2 = con2;
	}

	public String getCon3() {
		return this.con3;
	}

	public void setCon3(String con3) {
		this.con3 = con3;
	}

	public String getCon4() {
		return this.con4;
	}

	public void setCon4(String con4) {
		this.con4 = con4;
	}

	public String getCon5() {
		return this.con5;
	}

	public void setCon5(String con5) {
		this.con5 = con5;
	}

}
