package com.qf.dao.pojo;
// Generated 2017-7-11 12:41:52 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TRoute generated by hbm2java
 */
public class TRoute implements java.io.Serializable {

	private String id;
	private TTrain TTrain;
	private int siteorder;
	private String site;
	private int mile;
	private Date starttime;
	private Date endtime;
	private int staytime;
	private String con1;
	private String con2;
	private String con3;
	private String con4;
	private String con5;

	public TRoute() {
	}

	public TRoute(String id, TTrain TTrain, int siteorder, String site, int mile, Date starttime,
			Date endtime, int staytime) {
		this.id = id;
		this.TTrain = TTrain;
		this.siteorder = siteorder;
		this.site = site;
		this.mile = mile;
		this.starttime = starttime;
		this.endtime = endtime;
		this.staytime = staytime;
	}

	public TRoute(String id, TTrain TTrain, int siteorder, String site, int mile, Date starttime,
			Date endtime, int staytime, String con1, String con2, String con3, String con4, String con5) {
		this.id = id;
		this.TTrain = TTrain;
		this.siteorder = siteorder;
		this.site = site;
		this.mile = mile;
		this.starttime = starttime;
		this.endtime = endtime;
		this.staytime = staytime;
		this.con1 = con1;
		this.con2 = con2;
		this.con3 = con3;
		this.con4 = con4;
		this.con5 = con5;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public TTrain getTTrain() {
		return this.TTrain;
	}

	public void setTTrain(TTrain TTrain) {
		this.TTrain = TTrain;
	}

	public int getSiteorder() {
		return this.siteorder;
	}

	public void setSiteorder(int siteorder) {
		this.siteorder = siteorder;
	}

	public String getSite() {
		return this.site;
	}

	public void setSite(String site) {
		this.site = site;
	}

	public int getMile() {
		return this.mile;
	}

	public void setMile(int mile) {
		this.mile = mile;
	}

	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	public int getStaytime() {
		return this.staytime;
	}

	public void setStaytime(int staytime) {
		this.staytime = staytime;
	}

	public String getCon1() {
		return this.con1;
	}

	public void setCon1(String con1) {
		this.con1 = con1;
	}

	public String getCon2() {
		return this.con2;
	}

	public void setCon2(String con2) {
		this.con2 = con2;
	}

	public String getCon3() {
		return this.con3;
	}

	public void setCon3(String con3) {
		this.con3 = con3;
	}

	public String getCon4() {
		return this.con4;
	}

	public void setCon4(String con4) {
		this.con4 = con4;
	}

	public String getCon5() {
		return this.con5;
	}

	public void setCon5(String con5) {
		this.con5 = con5;
	}

}
