package com.qf.dao.pojo;
// Generated 2017-7-11 12:41:52 by Hibernate Tools 4.3.1.Final

/**
 * TCarriage generated by hbm2java
 */
public class TCarriage implements java.io.Serializable {

	private int id;
	private TTrain TTrain;
	private int cnumber;
	private short seatnumber;
	private int ctype;
	private String con1;
	private String con2;
	private String con3;
	private String con4;
	private String con5;

	public TCarriage() {
	}

	public TCarriage(int id, TTrain TTrain, int cnumber, short seatnumber) {
		this.id = id;
		this.TTrain = TTrain;
		this.cnumber = cnumber;
		this.seatnumber = seatnumber;
	}

	public TCarriage(int id, TTrain TTrain, int cnumber, short seatnumber, int ctype, String con1,
			String con2, String con3, String con4, String con5) {
		this.id = id;
		this.TTrain = TTrain;
		this.cnumber = cnumber;
		this.seatnumber = seatnumber;
		this.ctype = ctype;
		this.con1 = con1;
		this.con2 = con2;
		this.con3 = con3;
		this.con4 = con4;
		this.con5 = con5;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public TTrain getTTrain() {
		return this.TTrain;
	}

	public void setTTrain(TTrain TTrain) {
		this.TTrain = TTrain;
	}

	public int getCnumber() {
		return this.cnumber;
	}

	public void setCnumber(int cnumber) {
		this.cnumber = cnumber;
	}

	public short getSeatnumber() {
		return this.seatnumber;
	}

	public void setSeatnumber(short seatnumber) {
		this.seatnumber = seatnumber;
	}

	public int getCtype() {
		return this.ctype;
	}

	public void setCtype(int ctype) {
		this.ctype = ctype;
	}

	public String getCon1() {
		return this.con1;
	}

	public void setCon1(String con1) {
		this.con1 = con1;
	}

	public String getCon2() {
		return this.con2;
	}

	public void setCon2(String con2) {
		this.con2 = con2;
	}

	public String getCon3() {
		return this.con3;
	}

	public void setCon3(String con3) {
		this.con3 = con3;
	}

	public String getCon4() {
		return this.con4;
	}

	public void setCon4(String con4) {
		this.con4 = con4;
	}

	public String getCon5() {
		return this.con5;
	}

	public void setCon5(String con5) {
		this.con5 = con5;
	}

}
