package com.qf.dao.pojo;
// Generated 2017-7-11 12:41:52 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TUser generated by hbm2java
 */
public class TUser implements java.io.Serializable {

	private int id;
	private String username;
	private String password;
	private String realname;
	private int sex;
	private String uidnumber;
	private String tel;
	private int utype;
	private String urole;
	private String con1;
	private String con2;
	private String con3;
	private String con4;
	private String con5;
	private Set TOrderses = new HashSet(0);

	public TUser() {
	}

	public TUser(int id, String username, String password, String realname, int sex, String uidnumber,
			String tel, int utype) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.realname = realname;
		this.sex = sex;
		this.uidnumber = uidnumber;
		this.tel = tel;
		this.utype = utype;
	}

	public TUser(int id, String username, String password, String realname, int sex, String uidnumber,
			String tel, int utype, String urole, String con1, String con2, String con3, String con4, String con5,
			Set TOrderses) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.realname = realname;
		this.sex = sex;
		this.uidnumber = uidnumber;
		this.tel = tel;
		this.utype = utype;
		this.urole = urole;
		this.con1 = con1;
		this.con2 = con2;
		this.con3 = con3;
		this.con4 = con4;
		this.con5 = con5;
		this.TOrderses = TOrderses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public int getSex() {
		return this.sex;
	}

	public void setSex(int sex) {
		this.sex = sex;
	}

	public String getUidnumber() {
		return this.uidnumber;
	}

	public void setUidnumber(String uidnumber) {
		this.uidnumber = uidnumber;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public int getUtype() {
		return this.utype;
	}

	public void setUtype(int utype) {
		this.utype = utype;
	}

	public String getUrole() {
		return this.urole;
	}

	public void setUrole(String urole) {
		this.urole = urole;
	}

	public String getCon1() {
		return this.con1;
	}

	public void setCon1(String con1) {
		this.con1 = con1;
	}

	public String getCon2() {
		return this.con2;
	}

	public void setCon2(String con2) {
		this.con2 = con2;
	}

	public String getCon3() {
		return this.con3;
	}

	public void setCon3(String con3) {
		this.con3 = con3;
	}

	public String getCon4() {
		return this.con4;
	}

	public void setCon4(String con4) {
		this.con4 = con4;
	}

	public String getCon5() {
		return this.con5;
	}

	public void setCon5(String con5) {
		this.con5 = con5;
	}

	public Set getTOrderses() {
		return this.TOrderses;
	}

	public void setTOrderses(Set TOrderses) {
		this.TOrderses = TOrderses;
	}

}
